# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'MovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieApp
     pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'RxDataSources', '~> 5.0'
    pod 'UIScrollView-InfiniteScroll'
end
